---
title: "SI_EM"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{SI_EM}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(ICASSP20.T6.R)
library(zeallot)
```

# User Input
```{r}
epsilon <- 0.15 # Percentage of replacement outliers
N_k <- 50 # Number of samples per cluster
nu <- 3 # DoF for t distribution
qH <- .8 # Tuning parameter for Huber distribution

# Create data
c(data, labels, r, N, K_true, mu_true, S_true) %<-% data_31(N_k, epsilon)

cH <- sqrt(stats::qchisq(qH, r))
bH <- stats::pchisq(cH^2, r+2) + cH^2/r*(1-stats::pchisq(cH^2, r))
aH <- gamma(r/2)/pi^(r/2) / ( (2*bH)^(r/2)*(gamma(r/2) - pracma::incgam(r/2, cH^2/(2*bH))) + (2*bH*cH^2*exp(-cH^2/(2*bH)))/(cH^2 - bH * r))

g <- list(gaus = function(t) g_gaus(t, r),
        t = function(t) g_t(t, r, nu),
      huber = function(t) g_huber(t, r, list(cH, bH, aH)))

psi <- list(gaus = function(t) psi_gaus(t),
        t = function(t) psi_t(t, r, nu),
        huber = function(t) psi_huber(t, r, list(cH, bH)),
        tukey = function(t) psi_tukey(t, cT)
        )

x <- seq(-20,20,.1)
y <- seq(-20,20,.1)
grd <- pracma::meshgrid(x, y)
g_names <- c("Gaussian", "t", "Huber")

plot_scatter(cbind(labels, data), K_true, r)

for(m in 1:K_true){
  Z <- Rfast::dmvnorm(cbind(c(grd$X), c(grd$Y)), mu_true[,m], S_true[,,m])
  Z <- pracma::Reshape(Z, dim(grd$X)[1], dim(grd$X)[2])
  graphics::contour(x, y, t(Z), col = grDevices::rainbow(12), add = TRUE)
}

graphics::title("Model True", xlab = "Feature 1", ylab = "Feature 2")


```

# EM

```{r}
for(i in 1:3){ 
  c(mu_est, S_est, t, R) %<-% EM_RES(data, K_true, g[[i]], psi[[i]])
  
  plot_scatter(cbind(labels, data), K_true, r)
  for(m in 1:K_true){
    Z <- Rfast::dmvnorm(cbind(c(grd$X), c(grd$Y)), mu_est[,m], S_est[,,m])
    Z <- pracma::Reshape(Z, dim(grd$X)[1], dim(grd$X)[2])
    graphics::contour(x, y, t(Z), col = grDevices::rainbow(12), add = TRUE)
  }
  graphics::title(paste("Model ", g_names[[i]]), xlab = "Feature 1", ylab = "Feature 2")
  
}
```

